### ISSUE TITLE
Data too long for column url_key

### ISSUE THREAD

**Issue by duyhoan1710** [nodeonline/nodejscart#13]
- Create or Edit product
- nhập text quá dài tại field url_key

- Api: /admin/product/save

![image](https://user-images.githubusercontent.com/45579899/144756336-88b715c6-f0ef-4163-92ce-04f40ae24897.png)

**Comment by nodeonline** [comment]
Thanks @duyhoan1710 ,

For now, We will display an error message explaining the error. We will improve the form validation later

Thanks
