### ISSUE TITLE
Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [nodeonline/nodejscart#19]
Hello,
I have seen your project and your project is currently missing the Code of Conduct. If you want to add one, then I can submit a PR including that. In that case, I would need your contact address (email address) so that I can add it to the Code of Conduct as well. Please let me know what do you think about this.

**Comment by nodeonline** [comment]
Hi @FahimFBA 

I welcome your PR. I suggest to use the template from Github.
For now you can use this email: support@nodejscart.com

Thanks
